### ISSUE TITLE
Propose some additional features, such as microphone adjustment, recording volume (gain), and several other recording file formats on the Audio Recorder 0.5.24 application

### ISSUE THREAD

**Issue by ammarraisafti** [Dimowner/AudioRecorder#10]
# Introduction
Fast and lightweight Audio Recorder application. Ad-free

An audio recorder is an open source application making the audio recording experience easy.
The application is optimized for the fastest possible start and helps to not miss important sounds for users.

**Repository**
https://github.com/Dimowner/AudioRecorder

# Components
The components (Features) I want to suggest is:
* 1.Microphone adjustment.
* 2.Recording volume (gain).
* 3.Several other recording file formats, such as mp3, 3GPP-AMR(low quality, save memory).

Audio Recorder has a very good function, you can record directly using this application. In terms of function, indeed this application has a very good function. I really appreciate the developer of this project.

On the one hand, I am very impressed with this application that looks very simple and cool. But I think, the Audio Recorder application still needs to be developed to make this application more interesting. There are so many other similar applications that have the same function, I think developers don't just rely on functionality, but also have to think about user experience, and a better and more interesting impression on them.

Therefore, I want to suggest some features for the Audio Recorder application. I hope my suggestions can be an additional idea for developers to make the Audio Recorder application more attractive.

# Proposal description
**Microphone adjustment**
We recommend that the developer add this feature in the application settings section, and modify the section to make it easier for users. Press the button, make noise to determine the maximum gain factor, the developer must give the user the option to activate the device's auto gain control. The developer must add a calibration feature, and reset it in it, as well as mic level information after calibrating.

**Recording volume (gain)**
We recommend that developers add this feature in the application settings section. And giving the user the choice to change the recording volume, 0 db is the default value, and positive means the volume of the recording is louder. The developer must modify the section as best as possible, so that users can access it easily and quickly when changing the volume of recordings.

**Several other recording file formats, such as mp3, 3GPP-AMR(low quality, save memory)**
The developer must modify the format feature in the application settings section to add mp3 and 3GPP-AMR recording formats, and access to use it.

# Mockups / Examples
Below I will show examples of locations or illustrations if the features I recommend are implemented by the Developer.
![Screenshot_2019-03-29-23-12-16-picsay.jpg](https://cdn.steemitimages.com/DQmULy46WdzajR4rh4LVKuo2FkX1BsH7zemDpZ5tCv8ny3E/Screenshot_2019-03-29-23-12-16-picsay.jpg)

![Screenshot_2019-03-29-23-12-16-picsay.jpg](https://cdn.steemitimages.com/DQmWap9x1N47BEDDQMuMhFxr4C6xsr49UoQJADPRrvwxmAC/Screenshot_2019-03-29-23-12-16-picsay.jpg)

![Screenshot_2019-03-29-23-12-16-picsay.jpg](https://cdn.steemitimages.com/DQmPQhECDs7gxGunmZWNt7iTnAgYTYhY8ntr3MxiJXvVCZ6/Screenshot_2019-03-29-23-12-16-picsay.jpg)

![Screenshot_2019-03-29-23-12-16-picsay.jpg](https://cdn.steemitimages.com/DQmYzjfEnY8et2jvSyq3SiNzGTHVxWnAB8aJhqupNJbhuEU/Screenshot_2019-03-29-23-12-16-picsay.jpg)

![Screenshot_2019-03-29-23-30-19-picsay.jpg](https://cdn.steemitimages.com/DQmfEhbiE15yQjcNPnWr62zHo5LMc53yzQqHcus2s3zLD5x/Screenshot_2019-03-29-23-30-19-picsay.jpg)

# Benefits
**Microphone adjustment**
With the Microphone adjustment feature, users can calibrate the microphone, to get very satisfying and quality audio recordings. And that is a big advantage for users, they can also activate the device's auto gain control feature.

**Recording volume (gain)**
With the Recording volume (added) feature, users can change the recording volume, which is 0 db is the default value, and positive means the volume of the recording is louder. Users can record audio clearly, even though their device is in the pocket. The resulting audio recordings are very clear. And it was amazing and spoiled the users of this application.

**Several other recording file formats, such as mp3, 3GPP-AMR(low quality, save memory)**
After the developer adds mp3 and 3GPP-AMR formats, the available format options will be more complete in this application. Users can record audio using the low quality mp3 or 3GPP-AMR format and it will save memory on their device. This is perfect for those who have a small storage space.

# Conclusion
To implement the features above, developers may need to make major improvements. And in my opinion, it doesn't matter because it will have a good effect later.

The features that I recommend are certainly very useful because it will improve the user experience later. And this will add value to the Audio Recorder application. And I hope, the Audio Recorder application developer will soon be able to implement this suggestion.

**Comment by Dimowner** [comment]
Thank you for the detailed proposal. Yes, I'm thinking about adding more recording formats. Probably will add mp3 and 3gp in future releases. About another 2 requests, I can't say anything because I need to investigate them.
I think in the app description I need to add a list of features which will be added in future releases.
