### ISSUE TITLE
When pressing the delete button, it permanently deletes the previous recording

### ISSUE THREAD

**Issue by marcel263** [Dimowner/AudioRecorder#102]
Version 0.9.26 on samsung OneUI device.

Record, then stop recording. Then press the garbage bin icon to delete.

In actuality, it keeps the present recording, but it deletes the previous one - permanently.

In the folder `Android/data/com.dimowner.audiorecorder/files/Music/records` (accessable by USB MTP connection from a PC), the disappeared file is mentioned, by its size of 0 bytes. Alternatively, use the built-in file manager, result is the same.

So beware, despite all the good work, the app has a serious flaw making it unsuitable for safe work.

**Comment by Dimowner** [comment]
This issue was fixed in this PR: https://github.com/Dimowner/AudioRecorder/pull/116

Updated record panel buttons. Removed ability to delete recorded progress when recording paused.
