### ISSUE TITLE
Delete button while recording incorrectly deletes old recordings instead of current one

### ISSUE THREAD

**Issue by chrisdiamand** [Dimowner/AudioRecorder#104]
Hi - thanks for this awesome app! It looks lovely, playback is really easy to navigate, and the recordings sound great.

However, I have noticed the following issue. To reproduce it:

- Assume there are some pre-existing recordings
- Press record from the main screen (recording starts)
- Press "pause" to stop recording
- Press the delete button (bin with an "X" on it)
- Press "Yes" to confirm

I'd expect this to delete what was just recording - but *instead it deletes the most recent recording from the list of pre-existing recordings, and replaces it with what was just recorded*.

This is obviously a pretty severe issue as it causes data loss with no way to restore the old recording.

**Comment by Dimowner** [comment]
Thanks for reporting the issue. Looks like this is a very critical bug. Will try to fix it for the next app release.

**Comment by chrisdiamand** [comment]
Amazing thank you!

**Comment by Dimowner** [comment]
This issue was fixed in this PR: https://github.com/Dimowner/AudioRecorder/pull/116

Updated record panel buttons. Removed ability to delete recorded progress when recording paused.
