### ISSUE TITLE
Play Store link no longer working

### ISSUE THREAD

**Issue by Mennaruuk** [Dimowner/AudioRecorder#110]
https://play.google.com/store/apps/details?id=com.dimowner.audiorecorder
![Screenshot 2024-04-29 at 01-19-58 Not Found](https://github.com/Dimowner/AudioRecorder/assets/52135169/51b23160-47f8-4aac-974c-df60d0638165)

**Comment by Dimowner** [comment]
The app has been removed from Google Play Market. Need to update target SDK and resolve Data safety form issue.
Will try to resolve these issues and publish a new release soon.

**Comment by Dimowner** [comment]
The app is available on Google Play store again
