### ISSUE TITLE
[Feature Request] Change Save Location

### ISSUE THREAD

**Issue by tnyeanderson** [Dimowner/AudioRecorder#15]
Thank you for your hard work with this great app! I'm not sure what "save to public dir" means in the settings, but I think adding an option to set the location where recordings are saved would be valuable in this app. A button that opens up the file browser, where the user selects a folder to save the recordings to, would be very helpful for my use case.

Thanks again!

**Comment by protonpony** [comment]
I second that request. Someone with your skill level can add the feature with very little effort. I'd even consider creating a fork just to save to my SD card.

**Comment by Dimowner** [comment]
Ok, I will investigate if I will be able to add this feature

**Comment by Dimowner** [comment]
Starting from Android 10 there were added significant storage access restrictions. Now it is not possible to implement this feature for this application.
