### ISSUE TITLE
How to use WavRecorder class to generate .m4a file

### ISSUE THREAD

**Issue by chitrang200889** [Dimowner/AudioRecorder#22]
Hey, I am facing some initial delay issues with MediaRecorder class in my app. However, there is no delay with the AudioRecord class. But I need to save file .m4a format.

So the question is how to use the WavRecorder class to save the recording as .m4a file. 

Any help would be highly appreciated, thanks in advance.

**Comment by Dimowner** [comment]
WavRecorder intended to record Wav record not .m4a. I don't see a how we can do this
