### ISSUE TITLE
Suggest Migrate from SQLiteOpenHelper to Room ORM

### ISSUE THREAD

**Issue by mohsenpakzad** [Dimowner/AudioRecorder#23]
Nowadays, **orms** make working with database much easier, they are create and manage tables and models by it's own and no need for writing queries and engage yourself in it's hardships.
I searched a lot and find that best **orm** choice for android that supported and recommended by Google is **Room**.
Here I a put the link for you: [Room Persistence Library](https://developer.android.com/topic/libraries/architecture/room).
Let me know If you want any help for migration.

**Comment by Dimowner** [comment]
SQLite was selected intentionally. Original idea of the app was to not use any dependencies and make apk as small as possible. Now I not considering moving to the Room because it requires a lot changes and efforts.
