### ISSUE TITLE
File lost after recording ?and renaming?

### ISSUE THREAD

**Issue by davious** [Dimowner/AudioRecorder#27]
I'm losing recordings.

Pixel 1 device

I record and try to rename the file;
I then get told by the app that the file cannot be found.

When I look in the file manager, I see neither the original filename not the filename I tried to rename it to.

I really like this app, but I can't use it if it losses my recordings.

**Comment by Dimowner** [comment]
This issue has to be fixed in the recent update v0.8.4
Is it still present?

**Comment by davious** [comment]
Works for me. Thank you. 👏
