### ISSUE TITLE
Feature Request : Add trimmer in app

### ISSUE THREAD

**Issue by shwetachauhan-simform** [Dimowner/AudioRecorder#28]
It's really nice and you added all feature. If you add trimmer functionality like https://online-voice-recorder.com/ 
it would be more helpful

**Comment by shwetachauhan-simform** [comment]
Can you please help in adding trimmer? I am stuck here. Anyone who can add trimmer?

**Comment by yephny** [comment]
I agree, this could be a handy feature. It's partially implemented in [Audio Recorder on _F-Droid](https://www.f-droid.org/packages/com.github.axet.audiorecorder/) but it's unfortunately primitive, you can only trim recordings you haven't saved yet and you can't trim a specific portion, instead it trims everything after where you place the cursor.

**Comment by ShwetaChauhan18** [comment]
@yephny : I have added this feature using your code. I will release it ASAP.

**Comment by Dimowner** [comment]
This feature it quite complicated to implement. Already did a research how to implement it. It has multiple corner cases. Considering to add it as a paid feature for users.
