### ISSUE TITLE
[Feature Request] Date and time representation in a file naming convention

### ISSUE THREAD

**Issue by n0v0leg** [Dimowner/AudioRecorder#29]
Request: Please provide a file naming convention with an unambiguous date and time representation, where values are ordered from the largest to smallest unit of time.

Reason 1: Current convention does not allow files to be naturally sorted by name.
Reason 2: Current convention is ambiguous for the international users since date and time representation vary by country.

A minimal solution would be to modify the current convention by swapping the day and the year:
`2020.05.19 17.31.00`
An orthodox solution would be to adhere to an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard, for example:
`20200519173100+0300`
Personally, I would prefer something which resembles the default android camera app naming convention, by replacing `IMG`/ `VID` prefix with `REC` or `AUD`:
`REC_20200519_173100`
`AUD_20200519_173100`

**Comment by n0v0leg** [comment]
The minimal solution I proposed is already implemented: [TimeUtils.java#L46](https://github.com/Dimowner/AudioRecorder/blob/7bf4040aacc6de59a5338d370c12c0bae369c062/app/src/main/java/com/dimowner/audiorecorder/util/TimeUtils.java#L46).

**Comment by Anton-V-K** [comment]
> A minimal solution would be to modify the current convention by swapping the day and the year:
> `2020.05.19 17.31.00`

That would be great!
An ideal solution would be to support printf-like or [strftime](http://www.cplusplus.com/reference/ctime/strftime/)-like custom format, so a user could compose any naming.

**Comment by mmoole** [comment]
yes, as this could be just additional option(s) in the drowpdown menu, no need to replace the existing ones.
I would prefer ISO date like ```yyyy-mm-dd HH-MM-SS```
That would be totally awesome!

**Comment by Dimowner** [comment]
Added naming format 'yyyy-MM-dd HH.mm.ss' in this commit https://github.com/Dimowner/AudioRecorder/commit/d90690a8408e153ec79f0ee99f8ee0e1d1abd31e
