### ISSUE TITLE
Incorrect layout with on-screen system buttons

### ISSUE THREAD

**Issue by Anton-V-K** [Dimowner/AudioRecorder#35]
I use Android 6.0 (iLA S1, 1920x1080) which has on-screen system buttons, and apparently the application cannot handle such layout properly since it shows its main window under the on-screen buttons, which block access to app UI elements.
Consider to the screenshot below:
![Screenshot_20200806-205927-25](https://user-images.githubusercontent.com/20116984/89590113-d2456280-d84f-11ea-8fd1-30d3267634aa.jpg)
I was unable to touch Reset or Apply buttons, because they went under the on-screen system buttons.

**Comment by Dimowner** [comment]
This bug is fixed since v0.9.5
