### ISSUE TITLE
WavRecorder write file loss 44 bytes

### ISSUE THREAD

**Issue by pyzhangfan** [Dimowner/AudioRecorder#49]
RandomAccessFile write will overwrite the original content,so wav file loss 44 bytes data;
I suggest writing 44 bytes of blank data before recording. 

and totalAudioLen ,totalDataLen is wrong.(8 bytes smaller)
Thank you

**Comment by kresle** [comment]
This would cause huge trouble for PCM_24 AudioFormat. But the app itself does not support customizing the AudioFormat, anyway. When I was modifying the code to enable customizing audio sources, there was a USB hardware that could only output PCM_24, and I was tortured by this bug for a long time.

**Comment by Dimowner** [comment]
Fixed in this PR: https://github.com/Dimowner/AudioRecorder/pull/122
