### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [Dimowner/AudioRecorder#5]
Congrats to your app! May I ask if you'd consider an alternative download source for those without Google apps on their devices (and avoiding playstore)? You could e.g. use [tags](https://github.com/Dimowner/AudioRecorder/releases) for your releases and attach the APK to it (many projects do so – and from there I could fetch it for [my repo](https://apt.izzysoft.de/fdroid) and keep it automatically up-to-date, so folks can use the F-Droid client to install and update it).

Speaking of F-Droid: having your app added to the official repo would certainly be great. But that would need a build flavor without Fabric and Crashlytics.

Thanks in advance for considering!

**Comment by Dimowner** [comment]
Published a new release with attached APK. 
Also, I will consider publishing the app on F-Droid but maybe later.

**Comment by IzzySoft** [comment]
Thanks a lot! Just added it (will show up tomorrow). Would be great if you could remove Crashlytics (not permitted in the main repo, and considered a Tracker – Google already amasses enough data on us). If you need some analytics/crash reporting, ACRA is considered acceptable (also by F-Droid itself), and comes pretty privacy-friendly by default.

Let me know if you need help getting it into the main repo (when you're ready for that). As one of the maintainers, I might be able to give it :smiley:

**Comment by Dimowner** [comment]
Removed Crashlytics from the app in the master branch. All releases on GitHub will be without Crashlytics. But on Google Play I will publish with Crashlytics. I need some time to investigate ACRA.

**Comment by IzzySoft** [comment]
Great, thanks! Will remove the Tracking flag then tonight (after my updater fetched the new version). And yes, of course you first need to see if you can work with ACRA. If you're fine with having the tracking-free version on the F-Droid main repo (and there's a flavor/build-variant to build it), I gladly help you getting your app into the main repo. Just let me know. And as I wrote, if you later decide for ACRA, that shouldn't be an issue.

**Comment by IzzySoft** [comment]
There's a [request for packaging at F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1321) for a while, which I've just updated now. Looks pretty good. If you could make `versionCode` and `versionName` in your `build.gradle` "literals" (i.e. no variables or function calls), we could give that a try. Literal values are required for automated update checks, which only scan the gradle using regular expressions, and compare the values against the tags plus the latest build we have to see if an update is available.

**Comment by Dimowner** [comment]
Done

**Comment by IzzySoft** [comment]
Thanks a lot! I've just opened a PR providing you with Fastlane metadata; F-Droid would automatically pull and use them, so you can maintain summary, description, screenshots etc. yourself without needing to open merge requests for each change. My repo uses them as well. And AFAIK, using the Fastlane binaries you could even use this for deployment to Play Store.

Once that's merged and tagged, please ping me again and I'd process above mentioned MR. Having meanwhile advanced myself to "junior packager", I'm optimistic of having your app added within a week or two from that point.

**Comment by IzzySoft** [comment]
@Dimowner any ETA for the next release? The [MR at F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9194) is currently stuck waiting for that, as Fastlane was not yet tagged.

**Comment by IzzySoft** [comment]
@Dimowner Congrats, your app is now available at F-Droid (showed up there 10 days ago)! Do you want me to keep it in my repo nevertheless, or shall I remove it from there, as I usually do at this point? Some arguments (pros and cons) can be found [on this wiki page](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ#why-are-some-apps-available-in-both-repos). That decided, this issue can finally be closed :smiley:

**Comment by IzzySoft** [comment]
@Dimowner any answer to my last question (on whether I shall keep your app in my repo)? If not, I'd simply remove it from there (as I usually do when an app reaches F-Droid.org) in a week or so.
