### ISSUE TITLE
What is the INTERNET permission used for?

### ISSUE THREAD

**Issue by IzzySoft** [Dimowner/AudioRecorder#64]
Your app requests the `INTERNET` permission, but I couldn't figure out what it might be needed/used for. Maybe it could be removed?

**Comment by Dimowner** [comment]
INTERNET permission is for Firebase Crashlytics that added to the app that published on Google Play.  This permission can be removed the app releases on F-droid

**Comment by Dimowner** [comment]
INTERNET permission was removed in this PR: https://github.com/Dimowner/AudioRecorder/pull/116

**Comment by IzzySoft** [comment]
Thanks!
