### ISSUE TITLE
Discussion Related VOIP Call Recording

### ISSUE THREAD

**Issue by Zulqurnain** [Dimowner/AudioRecorder#7]
I tried to record VOIP calls using your code, but I couldn't do so, I just tried your recorder code for recording WhatsApp recording of calls but recorder didn't start.
What are your suggestions for me to do this task and do you have any help/source code for this matter?

**Comment by Dimowner** [comment]
Audio Recorder can't record calls, because that functionality is not implemented. I didn't investigate how this functionality can be added. Unfortunately, I don't have source code with example. I can't help you for now

**Comment by Zulqurnain** [comment]
No problem
