### ISSUE TITLE
Loosing recordings because of missing autosave

### ISSUE THREAD

**Issue by 8zgs4gt** [Dimowner/AudioRecorder#77]
How to reproduce(example):
Start application. Lock the phone. The application is still recording in the background. Now long press the powerbutton of the phone. Confirm for example reboot.
After the phone start up again, the whole recording is gone. There is a empty file left with 0 seconds of recording.

Please add the functionality to not loose recording when phone turns off(power button, empty battery, ...)

**Comment by 8zgs4gt** [comment]
Still need this autosave functionality.

**Comment by Dimowner** [comment]
Added autosave before reboot or shutdown in this PR: https://github.com/Dimowner/AudioRecorder/pull/118

Next step is add max record duration and auto start a new recording after reach max duration. This feature should protect from lose long recordings, only the last recorded section getting lost in case of something unexpected happened.
