### ISSUE TITLE
Copy app 

### ISSUE THREAD

**Issue by WelkinBunbury** [Dimowner/AudioRecorder#81]
https://play.google.com/store/apps/details?id=com.sladjan.audiorecorder

This app called 'voice rcorder' on playstore is a copy of your app, closed source with adds and payment.

I humbly ask everyone who see this message to report this all on playstore.

Also a github page called 'hall of shame' for all those people wh copies your work without following the FOSS policy should be put together. 

![Imagepipe_1.jpg](https://user-images.githubusercontent.com/33565456/170410428-d00c5c1a-5c65-4b8b-a08e-a14a403932db.jpg)

**Comment by illuminixmusic** [comment]
But this is totally free open source and ad free.
