### ISSUE TITLE
Deleting active recording does not work

### ISSUE THREAD

**Issue by marcel263** [Dimowner/AudioRecorder#86]
Press the delete button while recording
Notice how the recording stops but it still remains in the list

Somehow this feature used to work. There may be a database problem 

Logs are absent but will try
0.9.26

**Comment by Dimowner** [comment]
This issue was fixed in this PR: https://github.com/Dimowner/AudioRecorder/pull/116

Updated record panel buttons. Removed ability to delete recorded progress when recording paused.
