### ISSUE TITLE
better compression

### ISSUE THREAD

**Issue by rafiip** [Dimowner/AudioRecorder#9]
is it possible for you to add a better compression so that recording takes less of space on the device? currently it is good for m4a format but certainly not enough

**Comment by Dimowner** [comment]
Added in the app settings ability to select recording bitrate 24kbps. Previously smallest bitrate was 48kbps. With that bitrate, record size became about 2 times smaller than with 48kbps.

**Comment by PontiacCZ** [comment]
I used to use 24 kbps, it was perfect quality for recording mono voice on 16 kHz. But it was removed about 2 months ago so we're back to the minimum of 48 kbps.  What happened?

![image](https://user-images.githubusercontent.com/9153595/82832266-e87f8b80-9eba-11ea-8b32-3590f1855d32.png)

**Comment by Dimowner** [comment]
There is 3gp format supported now. It provides good compression and make records with 12 kbps quality.
