### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by DevTrinh** [Dimowner/AudioRecorder#96]
can someone tell me about the commercial copyright, i want to use it for commercial purposes, i'm a newbie, i don't understand this issue well. Thanks for reading, please help

**Comment by Mennaruuk** [comment]
It's licensed under Apache 2.0. You can use, modify, and distribute the licensed work for any commercial purpose. There is no need to pay any fees or royalties to the original author, though I'm sure they'd appreciate any donations. However, you do need to include the original copyright notice, disclaimer, and if the program is distributed, the license itself. That's the beauty of Apache 2.0! It's great if you don't want to deal with copyleft restrictions while maintaining some trademarks and logo/brand rights.
